In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import scale 
from sklearn.preprocessing import StandardScaler
from sklearn import model_selection
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import train_test_split
from sklearn.cross_decomposition import PLSRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from scipy.signal import savgol_filter

In [19]:
data_traits = pd.read_csv('2022_sorghum_traits.csv', dtype = {'Genotype' : 'category', 'Rep': 'category' , 'Leaf_Num' : 'category'})

In [37]:
data_reflectance = pd.read_csv('Sorghum_2022_reflectance.csv', dtype={'Genotype' : 'category', 'Rep': 'category' , 'Leaf_Num' : 'category', 'Leaf_pos' : 'category'})

In [38]:
data_traits = data_traits.iloc[: , 0:10]

In [39]:
data_traits = data_traits.loc[data_traits['CHLp1'].notnull() , :]

In [40]:
data_traits

,Genotype ID,Accession,Genotype,Rep,Leaf_num,CHLp1,CHLp2,CHLp3,FW,LA
0,GREENLEAF,PI 659692,1,1,1.0,367.4,472.9,399.7,4.45,281.59
1,GREENLEAF,PI 659692,1,1,2.0,399.7,739.3,357.8,3.45,225.36
2,GREENLEAF,PI 659692,1,1,3.0,439.2,362.3,347.7,1.65,125.04
3,GREENLEAF,PI 659692,1,2,1.0,447.1,141.9,160.9,4.45,249.96
4,GREENLEAF,PI 659692,1,2,2.0,325.2,481.0,322.5,1.90,144.58
...,...,...,...,...,...,...,...,...,...,...
433,RTx2909,PI 598 69,68,1,2.0,293.6,310.7,304.7,8.70,380.90
434,RTx2909,PI 598 69,68,1,3.0,240.8,239.5,305.8,8.20,380.94
435,RTx2909,PI 598 69,68,2,1.0,279.1,254.0,263.2,8.35,372.25
436,RTx2909,PI 598 69,68,2,2.0,252.7,308.1,389.5,9.05,341.73
437,RTx2909,PI 598 69,68,2,3.0,232.1,283.0,388.4,8.80,352.01

In [41]:
data = pd.merge(data_traits, data_reflectance, how='outer' )

In [43]:
data = data.loc[data['CHLp1'].notnull() , :]

In [47]:
data.to_csv(r'/home/schnable/Downloads/sorghum_2022_whole.csv', index = None)